version: '3.8'

services:
  user-service:
    build: ./user-service
    ports :
      - "5001:5001"

  order-service:
    build: ./order-service
    ports:
      - "5002:5002"

  api-gateway:
    build: ./api-gate
    ports:
      - "80:80"
    depends_on:
      - user-service
      - order-service
